### ISSUE TITLE
About baidu tongji

### ISSUE THREAD

**Issue by becauseofAI** [cyent/markdown-with-mkdocs-material#2]
Why does Baidu statistics not work?

**Comment by cyent** [comment]
你什么信息都没提供，我怎么知道你为什么不行？。。。

**Comment by becauseofAI** [comment]
@cyent 
Because your page does not have Baidu statistics.

**Comment by cyent** [comment]
![image](https://user-images.githubusercontent.com/1782125/60476614-d72ffe00-9cae-11e9-917a-9bcab2868334.png)

**Comment by cyent** [comment]
![image](https://user-images.githubusercontent.com/1782125/60476695-1cecc680-9caf-11e9-9564-50fe4c944615.png)

**Comment by cyent** [comment]
![image](https://user-images.githubusercontent.com/1782125/60476799-853ba800-9caf-11e9-8d7f-8e4259aa93b2.png)
